### ISSUE TITLE
make buffs/debuffs additive

### ISSUE THREAD

**Issue by Lostmaniac9** [mashupstudios/dungeons-and-blasters#79]
Move speed, damage received, damage dealt, and resistance mods would be so much easier to math if they had additive scaling instead of multiplicative scaling

Not a high priority, but it would make stacking buffs/debuffs more much consistent and easier to balance

outside of the easier internal calculations there is zero advantage to this system outside of making my life so much harder

**Comment by KSamsoe** [comment]
Additive scaling becomes very problematic when you're receiving it from many different sources. It can quickly balloon out of control or drop below zero, and I imagine it will be a balancing nightmare to ensure this doesn't happen.
